AWSTemplateFormatVersion: '2010-09-09'
Description: GitHub OIDC provider + deploy role for vivekshukla75075/data-pipeline-country-population

Parameters:
  RepoOwner:
    Type: String
    Default: vivekshukla75075
  RepoName:
    Type: String
    Default: data-pipeline-country-population
  RoleName:
    Type: String
    Default: github-actions-deploy-role

Resources:
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        # GitHub OIDC thumbprint (Amazon Root CA 1)
        - 6938fd4d98bab03faadb97b34396831e3780aea1

  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GitHubOIDCProvider
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub "repo:${RepoOwner}/${RepoName}:*"

      Policies:
        - PolicyName: GitHubActionsDeployPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:

              # CloudFormation
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:ValidateTemplate
                Resource: "*"

              # Lambda
              - Effect: Allow
                Action:
                  - lambda:CreateFunction
                  - lambda:UpdateFunctionCode
                  - lambda:GetFunction
                Resource: "*"

              # S3
              - Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource: "*"

              # EventBridge + Logs
              - Effect: Allow
                Action:
                  - events:*
                  - logs:*
                Resource: "*"

              # IAM (for Lambda roles created by CFN)
              - Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:AttachRolePolicy
                  - iam:PassRole
                Resource: "*"

Outputs:
  RoleArn:
    Value: !GetAtt GitHubActionsRole.Arn